name: Deploy to Fly.io

on:
  push:
    branches:
      - main  # Replace with your branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Fly.io CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "$HOME/.fly/bin" >> $GITHUB_PATH

      - name: Set Fly.io API Token
        run: echo "FLY_API_TOKEN=${{ secrets.FLY_API_TOKEN }}" >> .env
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
